version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 141296
      POSTGRES_USER: postgres
      POSTGRES_DB: lovehub
    networks:
      - webnet
  mongodb:
    image: mongo
    networks:
      - webnet
  server:
    image: app
    build: ./app
    depends_on:
      - db
      - mongodb
    command:
      ["npm", "run", "start"]
    ports:
      - "4201:4200"
      - "5400:5400"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - webnet
networks:
  webnet:
# "npm", "rebuild", "node-sass", "--force",