export const usersList = [
    {
      id: <number>1,
      firstName: <string>'Admin',
      lastName: <string>'Admin',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'Administrator',
      registrationDate: '2001-01-02',
      lastActiveDate: '2018-10-01',
    },
    {
      id: <number>247731,
      firstName: <string>'User0',
      lastName: <string>'User0',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2012-01-02',
      lastActiveDate: '2018-11-01',
      age: <number>21,
      gender: <string>'Male'
    },
    {
      id: <number>905741,
      firstName: <string>'User1',
      lastName: <string>'User1',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2008-01-02',
      lastActiveDate: '2018-12-01',
      age: <number>42,
      gender: <string>'Female'
    },
    {
      id: <number>438961,
      firstName: <string>'User2',
      lastName: <string>'User2',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2015-01-02',
      lastActiveDate: '2018-13-01',
      age: <number>54,
      gender: <string>'Male'
    },
    {
      id: <number>155452,
      firstName: <string>'User3',
      lastName: <string>'User3',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2008-01-02',
      lastActiveDate: '2018-14-01',
      age: <number>59,
      gender: <string>'Female'
    },
    {
      id: <number>669339,
      firstName: <string>'User4',
      lastName: <string>'User4',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2016-01-02',
      lastActiveDate: '2018-15-01',
      age: <number>29,
      gender: <string>'Male'
    },
    {
      id: <number>857314,
      firstName: <string>'User5',
      lastName: <string>'User5',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'Moderator',
      registrationDate: '2011-01-02',
      lastActiveDate: '2018-16-01',
      age: <number>41,
      gender: <string>'Female'
    },
    {
      id: <number>874411,
      firstName: <string>'User6',
      lastName: <string>'User6',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'Moderator',
      registrationDate: '2010-01-02',
      lastActiveDate: '2018-17-01',
      age: <number>34,
      gender: <string>'Male'
    },
    {
      id: <number>694102,
      firstName: <string>'User7',
      lastName: <string>'User7',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2008-01-02',
      lastActiveDate: '2018-18-01',
      age: <number>36,
      gender: <string>'Female'
    },
    {
      id: <number>4240,
      firstName: <string>'User8',
      lastName: <string>'User8',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2003-01-02',
      lastActiveDate: '2018-19-01',
      age: <number>38,
      gender: <string>'Male'
    },
    {
      id: <number>2934,
      firstName: <string>'User9',
      lastName: <string>'User9',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2015-01-02',
      lastActiveDate: '2018-20-01',
      age: <number>22,
      gender: <string>'Female'
    },
    {
      id: <number>183733,
      firstName: <string>'User10',
      lastName: <string>'User10',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2006-01-02',
      lastActiveDate: '2018-21-01',
      age: <number>55,
      gender: <string>'Male'
    },
    {
      id: <number>667060,
      firstName: <string>'User11',
      lastName: <string>'User11',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2001-01-02',
      lastActiveDate: '2018-22-01',
      age: <number>27,
      gender: <string>'Female'
    },
    {
      id: <number>812395,
      firstName: <string>'User12',
      lastName: <string>'User12',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2014-01-02',
      lastActiveDate: '2018-23-01',
      age: <number>37,
      gender: <string>'Male'
    },
    {
      id: <number>573430,
      firstName: <string>'User13',
      lastName: <string>'User13',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2007-01-02',
      lastActiveDate: '2018-24-01',
      age: <number>48,
      gender: <string>'Female'
    },
    {
      id: <number>829486,
      firstName: <string>'User14',
      lastName: <string>'User14',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'Moderator',
      registrationDate: '2007-01-02',
      lastActiveDate: '2018-25-01',
      age: <number>59,
      gender: <string>'Male'
    },
    {
      id: <number>678402,
      firstName: <string>'User15',
      lastName: <string>'User15',
      isActive: true,
      isBaned: false,
      role: <string>'Moderator',
      registrationDate: '2002-01-02',
      lastActiveDate: '2018-26-01',
      age: <number>26,
      gender: <string>'Female'
    },
    {
      id: <number>811004,
      firstName: <string>'User16',
      lastName: <string>'User16',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'Moderator',
      registrationDate: '2012-01-02',
      lastActiveDate: '2018-27-01',
      age: <number>34,
      gender: <string>'Male'
    },
    {
      id: <number>450156,
      firstName: <string>'User17',
      lastName: <string>'User17',
      isActive: true,
      isBaned: false,
      role: <string>'User',
      registrationDate: '2015-01-02',
      lastActiveDate: '2018-28-01',
      age: <number>55,
      gender: <string>'Female'
    },
    {
      id: <number>838009,
      firstName: <string>'User18',
      lastName: <string>'User18',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2017-01-02',
      lastActiveDate: '2018-29-01',
      age: <number>47,
      gender: <string>'Male'
    },
    {
      id: <number>112007,
      firstName: <string>'User19',
      lastName: <string>'User19',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'Moderator',
      registrationDate: '2009-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>20,
      gender: <string>'Female'
    },
    {
      id: <number>675978,
      firstName: <string>'User20',
      lastName: <string>'User20',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2015-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>31,
      gender: <string>'Male'
    },
    {
      id: <number>245087,
      firstName: <string>'User21',
      lastName: <string>'User21',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2014-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>25,
      gender: <string>'Female'
    },
    {
      id: <number>147095,
      firstName: <string>'User22',
      lastName: <string>'User22',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2013-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>33,
      gender: <string>'Male'
    },
    {
      id: <number>5436097,
      firstName: <string>'User23',
      lastName: <string>'User23',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2012-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>38,
      gender: <string>'Female'
    },
    {
      id: <number>245086,
      firstName: <string>'User24',
      lastName: <string>'User24',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2011-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>29,
      gender: <string>'Male'
    },
    {
      id: <number>987563,
      firstName: <string>'User25',
      lastName: <string>'User25',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2010-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>44,
      gender: <string>'Female'
    },
    {
      id: <number>586974,
      firstName: <string>'User26',
      lastName: <string>'User26',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2010-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>41,
      gender: <string>'Male'
    },
    {
      id: <number>109654,
      firstName: <string>'User27',
      lastName: <string>'User27',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2009-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>39,
      gender: <string>'Female'
    },
    {
      id: <number>196749,
      firstName: <string>'User28',
      lastName: <string>'User28',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2008-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>37,
      gender: <string>'Male'
    },
    {
      id: <number>356975,
      firstName: <string>'User29',
      lastName: <string>'User29',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2007-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>35,
      gender: <string>'Female'
    },
    {
      id: <number>583457,
      firstName: <string>'User30',
      lastName: <string>'User30',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2006-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>29,
      gender: <string>'Male'
    },
    {
      id: <number>195746,
      firstName: <string>'User31',
      lastName: <string>'User31',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate:  '2005-01-02',
      lastActiveDate:  '2018-30-01',
      age: <number>43,
      gender: <string>'Female'
    },
    {
      id: <number>196745,
      firstName: <string>'User32',
      lastName: <string>'User32',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2004-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>51,
      gender: <string>'Male'
    },
    {
      id: <number>967543,
      firstName: <string>'User33',
      lastName: <string>'User33',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2003-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>28,
      gender: <string>'Female'
    },
    {
      id: <number>497615,
      firstName: <string>'User34',
      lastName: <string>'User34',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2002-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>27,
      gender: <string>'Male'
    },
    {
      id: <number>858762,
      firstName: <string>'User35',
      lastName: <string>'User35',
      isActive: <boolean>true,
      isBaned: <boolean>false,
      role: <string>'User',
      registrationDate: '2001-01-02',
      lastActiveDate: '2018-30-01',
      age: <number>24,
      gender: <string>'Female'
    }
  ];
